### ISSUE TITLE
Allow shorter interval

### ISSUE THREAD

**Issue by KSXGitHub** [alexduf/gnome-github-notifications#12]
Allow below 60 seconds interval, e.g. 5 secs.

**Comment by alexduf** [comment]
I'm afraid I can't do that without violating their documentation here: https://developer.github.com/v3/activity/notifications/

>Notifications are optimized for polling with the "Last-Modified" header. If there are no new notifications, you will see a "304 Not Modified" response, leaving your current rate limit untouched. There is an "X-Poll-Interval" header that specifies how often (in seconds) you are allowed to poll. In times of high server load, the time may increase. Please obey the header.

`¯\_(ツ)_/¯`
