### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by 0xADD1E** [alexduf/gnome-github-notifications#13]
Debian buster / shell 3.28.2

Updating / exiting the settings dialog doesn't appear to update the settings in dconf

Easy enough to manually remedy by setting in dconf editor `/org/gnome/shell/extensions/github-notifications`, but this shouldn't be required

**Comment by 0xADD1E** [comment]
After a reinstall (for unrelated reasons) it seems to work as intended, so closing unless someone else can reproduce

**Comment by alexduf** [comment]
Glad it worked out :+1:
