### ISSUE TITLE
Feature Request: Reset notification count

### ISSUE THREAD

**Issue by divyanshu013** [alexduf/gnome-github-notifications#17]
Hi, love the extension. I've a feature request to reset the notification count when I click to open the notifications on my browser. I use a long sync time (around 10 minutes). Please let me know if this makes sense. I can also send a PR for this if the idea sounds good to you. Thanks :smile:

**Comment by alexduf** [comment]
Thanks!

I don't know how useful this might be, it will heavily depend on how individual people carry on their work.
I'd like to know this will be useful to more than one person before adding it in :)

**Comment by ericdallo** [comment]
Useful for me too :+1:

**Comment by alexduf** [comment]
Hey @divyanshu013 is your use case supported now that github has created a new swanky notification screen?

**Comment by divyanshu013** [comment]
Hey, yeah. You may close this or keep it open in case you want to track.
