### ISSUE TITLE
Only show count of particpating threads

### ISSUE THREAD

**Issue by salmanulfarzy** [alexduf/gnome-github-notifications#18]
This could be controlled with flag, similar to `hide-count`. With changes in these lines,

https://github.com/alexduf/gnome-github-notifications/blob/33a8704f1cdf9016474fbd31d9c54c4629ba98c2/extension.js#L33

https://github.com/alexduf/gnome-github-notifications/blob/33a8704f1cdf9016474fbd31d9c54c4629ba98c2/extension.js#L154

Modified it on my local setup, Could send a PR if interested. But setting up preference page seems bit confusing to me. How does value from xml schema are used in `extension.js` ? Manually defining `<key>` block for new option returns nothing from preference page ?

**Comment by alexduf** [comment]
Hey @salmanulfarzy, thanks for the report that's a good idea so I gave it a stab here https://github.com/alexduf/gnome-github-notifications/pull/19

I don't expect that to be merged before next year. If you're feeling adventurous do checkout the branch and see if that's what you had in mind.

I haven't even run the code so beware it's probably going to crash :D

**Comment by salmanulfarzy** [comment]
Closing this now since #19 is merged :tada:

**Comment by alexduf** [comment]
It's submitted for review, but got no progress on that front

**Comment by salmanulfarzy** [comment]
Yeah.. Just tried updating from extensions gallery and it reverted this changes. Until it's published, back to git repo. 

Saw you making change log through comments, Thank you for that. But is there any other way to keep change log between versions ? May be something like GitHub releases corresponding to published versions ?

So the latest version available is v13 on extensions page, May be a GitHub release with v13 as title for that would greatly help in keeping track of changes.

**Comment by alexduf** [comment]
> May be something like GitHub releases corresponding to published versions ?

That's a good shout. I'll start doing that from now on
