### ISSUE TITLE
No JS module 'tweener' found in search path with Gnome 3.38.1

### ISSUE THREAD

**Issue by ChristophWurst** [alexduf/gnome-github-notifications#26]
Hi :wave: 

I updated my system yesterday and that supposedly broke the Github notifications. This is what Gnome's extensions page shows me:

![Bildschirmfoto von 2020-10-09 10-35-01](https://user-images.githubusercontent.com/1374172/95561495-1bb25980-0a1b-11eb-94ff-002c8be3a916.png)

Any idea? I think this is not a problem unique to this extension but also seen with other ones, like https://github.com/codito/gnome-pomodoro/pull/517 for example.

**Comment by ChristophWurst** [comment]
https://github.com/alexduf/gnome-github-notifications/blob/8cef8ac56e104462e5a1a01e87267182b9a66de0/extension.js#L4 the import isn't even used. So this might be easy to fix :)

**Comment by ChristophWurst** [comment]
That does the trick indeed. I simply patched the file locally, logged out and in and my notification counter is back :rocket:

**Comment by alexduf** [comment]
I really appreciate the time and the bug report. I've merged the PR and packaged it, it's now submitted to the gnome team.

It can take a varying amount of time for their team to review it, but eventually it will make its way to the official store!
