### ISSUE TITLE
Instalation/Update Error

### ISSUE THREAD

**Issue by slottwo** [alexduf/gnome-github-notifications#29]
I had installed the extension through the gnome website, and it worked normally, but today I was notified of an update to it, I updated it through the website and it was showing an error label. In the Pop OS extension manager, I was able to open the extension settings, but not turn it on.
Then I remove it and tried to install manually with GitHub. And this was the answer:
```shell
khaled@pop-os: ~/.local/share/gnome-shell/extensions$ sudo git clone git@github.com:alexduf/gnome-github-notifications.git github.notifications@alexandre.dufournet.gmail.com

Cloning into 'github.notifications@alexandre.dufournet.gmail.com'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

*Some system Information:*
OS: Pop!_OS 20.04 LTS x86_64 
Kernel: 5.4.0-7642-generic 
Shell: bash 5.0.17 
Gnome Shell: 3.36.4

**Comment by alexduf** [comment]
Hey @slottwo 

Would you mind trying to install the extension like so instead? The error message makes me think you haven't configured your SSH keys to work with github yet.

`git clone https://github.com/alexduf/gnome-github-notifications.git github.notifications@alexandre.dufournet.gmail.com`

**Comment by slottwo** [comment]
It didn't show an error message, like a popup or text alert or trying to install extensions using GitHub, but a label written ERROR in this position:
![Captura de tela de 2020-10-23 17-40-57](https://user-images.githubusercontent.com/41028091/97052201-efd4bf00-1556-11eb-8d50-379b8037bec7.png)
As you can see, it doesn't appear anymore, but now I don't know exactly what it means, but in the top bar instead of 0 or another number it shows a "!", I don't know if it's an error, so to test I marked as unread two Notifications. I already put a regenerated token and restarted Gnome (Alt + F2, r, Enter). Also, when I click on the icon it takes me to the https://notifications/ page, which does not exist. (It should probably be https://github.com/notifications)
![Captura de tela de 2020-10-23 17-50-14](https://user-images.githubusercontent.com/41028091/97052918-47275f00-1558-11eb-8209-a76ca61803d0.png)
So to answer the second question I decided to uninstall and try it manually as you asked. (I restarted Gnome again after installation to try to prevent any conflicts)
The download went well this time.
I restarted the computer this time, but continued to experience the same problems, I checked the token and permissions (set as notifications only) and were correct. Was the "github handle" field to be filled with something?

**Comment by alexduf** [comment]
I'm not sure what happen!

Try putting `github.com` in the hostname, and ensuring you have a valid token in the github token as your screenshot doens't show one?

**Comment by slottwo** [comment]
> Try putting `github.com` in the hostname, 
It worked!
> and ensuring you have a valid token in the github token as your screenshot doens't show one?
I removed the token to take the screenshot for privacy and security reasons.

**Comment by alexduf** [comment]
>I removed the token to take the screenshot for privacy and security reasons.
that's wise

Strange I'll have to install that plugin again and see if the default `github.com` value is set.

Glad it works for you!
