### ISSUE TITLE
add homepage link to github page on extensions.gnome.org page

### ISSUE THREAD

**Issue by wbolster** [alexduf/gnome-github-notifications#3]
the summary says it all.

**Comment by alexduf** [comment]
Good idea, thanks!

**Comment by alexduf** [comment]
done here: https://github.com/alexduf/gnome-github-notifications/commit/1111fd2e53d44b26b993548a719af3c16bfe8d4c

**Comment by wbolster** [comment]
you should add the url also to the extension details via the extensions.gnome.org web interface. e.g.

![image](https://cloud.githubusercontent.com/assets/748944/20137024/624ec1ae-a678-11e6-8c27-b45c8f8fe8de.png)
