### ISSUE TITLE
Support for Gnome 40

### ISSUE THREAD

**Issue by magthe** [alexduf/gnome-github-notifications#32]
The most recent version of the extension doesn't work with the latest version of Gnome.

I'm no JS/Gnome developer so I'm afraid I can't help out with writing code, but please let me know if I can help out with testing or something else.

**Comment by magthe** [comment]
Some extra information: https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/

**Comment by raucao** [comment]
Just FYI: The following is the exception that is raised when trying to open the extension's settings. Maybe it helps.

---

The settings of extension github.notifications@alexandre.dufournet.gmail.com had an error:
```
TypeError: hideWidgetBox.pack_start is not a function
```

Stack trace:
```
buildPrefsWidget@/home/basti/.local/share/gnome-shell/extensions/github.notifications@alexandre.dufournet.gmail.com/prefs.js:28:17
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by papanito** [comment]
@raucao exact same here

**Comment by machitgarha** [comment]
@raucao 

The reason is simple: There is no `Box::pack_start` function going from GTK [3.x](https://developer.gnome.org/gtkmm/3.24/classGtk_1_1Box.html) to [4.x](https://developer.gnome.org/gtkmm/4.0/classGtk_1_1Box.html). As stated [here](https://developer.gnome.org/gtkmm-tutorial/stable/changes-gtkmm4.html.en), `Box::append` should be used instead.

**Comment by tim-hm** [comment]
Modified `metadata.json` locally and this branch is working on gnome 41.rc :partying_face:
