### ISSUE TITLE
hide icon when there are no notifications

### ISSUE THREAD

**Issue by wbolster** [alexduf/gnome-github-notifications#4]
the icon and the count should be hidden in case there are no notifications. right now this gives (branded) visual clutter. this extension is not intended as a permanently visible github shortcut button. :)

**Comment by wbolster** [comment]
additionally, i would want to disable the count completely. i am not interested in numbers in my menu bar.

**Comment by alexduf** [comment]
I may implement that as an option, I personally like to know my extension hasn't crashed and the number really is 0 😄

**Comment by wbolster** [comment]
i have a strong dislike for useless clutter. right now i have a github logo visible at all times. "these 16x16 pixels are kindly sponsored by  github" ;)

fwiw, my https://github.com/wbolster/nothing-to-say extension hides the icon

**Comment by alexduf** [comment]
Cheers, I'll have a look

**Comment by alexduf** [comment]
done here: https://github.com/alexduf/gnome-github-notifications/commit/605e6085c69bf286bdc1e668f76302a8cbec1aa4

**Comment by wbolster** [comment]
https://github.com/alexduf/gnome-github-notifications/commit/f9249363dc207a2b9a071e68660d19218369c8ac#commitcomment-19753824
