### ISSUE TITLE
Not running correctly on GNOME Shell 3.36.9 

### ISSUE THREAD

**Issue by bgolding355** [alexduf/gnome-github-notifications#45]
When I:
1. Install `Github Notifications` using the `Manual` instruction in the README
2. Open the `Extensions` Application and click on the gear icon associated with `Github Notification`

I see:
```
TypeError: box.append is not a function

Stack trace:
  makeLabeledOptionBox@/home/bgolding/.local/share/gnome-shell/extensions/github.notifications@alexandre.dufournet.gmail.com/prefs.js:29:9
  makeLabeledEntryOptionBox@/home/bgolding/.local/share/gnome-shell/extensions/github.notifications@alexandre.dufournet.gmail.com/prefs.js:48:17
  buildPrefsWidget@/home/bgolding/.local/share/gnome-shell/extensions/github.notifications@alexandre.dufournet.gmail.com/prefs.js:78:9
  _init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:207:40
  OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
  asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:132:13
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:175:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
  run@resource:///org/gnome/gjs/modules/script/package.js:222:19
  start@resource:///org/gnome/gjs/modules/script/package.js:206:5
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
  ```

Note that I am using: GNOME Shell 3.36.9 on Ubuntu 20.04

**Comment by alexduf** [comment]
Hi @bgolding355 that would be because the latest master is only compatible with gnome 40+

Either install the extension from extensions.gnome.org, or install this specific commit 214472571493101706927003c3ed71ae85dc5bae

**Comment by bgolding355** [comment]
@alexduf thanks. I notice that this project does not have any tags or releases.

It would be helpful to create some kind of compatibility chart. Something like tagging releases or adding something to the README about what to install based on your GNOME version

**Comment by alexduf** [comment]
Thanks for the feedback @bgolding355 I've made myself a note here
https://github.com/alexduf/gnome-github-notifications/issues/46
