### ISSUE TITLE
configurable refresh interval

### ISSUE THREAD

**Issue by wbolster** [alexduf/gnome-github-notifications#5]

**Comment by alexduf** [comment]
Hi there, thanks for the suggestion.

The reason I didn't put a refresh interval is because github are politely asking to follow their refresh interval.

> There is an "X-Poll-Interval" header that specifies how often (in seconds) you are allowed to poll. In times of high server load, the time may increase. Please obey the header.

https://developer.github.com/v3/activity/notifications/

We could of course not follow the rule but I don't think it would be a good idea.

**Comment by wbolster** [comment]
ah, great. but does it makes sense to increase the limit? e.g. check only once per hour instead of every minute.

**Comment by alexduf** [comment]
ah, I hadn't thought of that! Yes it makes sense and I'll take the biggest number between the conf and what github returns

**Comment by alexduf** [comment]
done here: https://github.com/alexduf/gnome-github-notifications/commit/f9249363dc207a2b9a071e68660d19218369c8ac
