### ISSUE TITLE
More intuitive way to get into settings

### ISSUE THREAD

**Issue by honza889** [alexduf/gnome-github-notifications#8]
Would be great, if right click on the icon would show some menu, or directly the settings dialog, which looks accessible only from Gnome Extensions web and it is not much easy to find it.
(or at least show config dialog instead of github web when exclamation mark indicate that connection failed)

**Comment by alexduf** [comment]
I agree that it's not super intuitive to find the settings, but I don't think right-click on the extension icon is a common pattern within the gnome ecosystem.

I'm not sure how other extensions are suggesting to go to the settings, have you got any example in mind @honza889 ?

**Comment by alexduf** [comment]
I've updated the description, maybe that will save some time for the next person installing it?

https://extensions.gnome.org/extension/1125/github-notifications/

**Comment by honza889** [comment]
Problem is, users can install the extension using Software center, into which navigates from Gnome Shell search...
will try to investigate better solution, but for failing connection icon to show config instead of github web (which can mislead him, that github login is ok, because he is logged in browser) would be appropriate, I believe...

**Comment by alexduf** [comment]
That's a good point. I have no clue how to do that but that must be possible. I'll check next time I'm bored :)

**Comment by MrxHouse** [comment]
I'd like to do it, I have it installed twice now. LOL.

Is there anyway to access it from the shell? (newb here, I will consult the documentation)

**Comment by alexduf** [comment]
@MrxHouse if you have installed it through https://extensions.gnome.org, there's a setting button right next to the extension here https://extensions.gnome.org/local/
If you have installed it via any other way, you can access the settings via gnome-tweak (you can install gnome-tweak via most distribution's package managers)

**Comment by paolobarbolini** [comment]
Since I'm learning how to make gnome extensions by modifying other people extensions, i like this one and I'm also participating in hacktoberfest I'll try to implement it.

**Comment by alexduf** [comment]
Great, PRs welcomed!
