### ISSUE TITLE
Support for GitHub Enterprise

### ISSUE THREAD

**Issue by ntkoopman** [alexduf/gnome-github-notifications#9]
Would be nice if there was support for self-hosted enterprise versions. This would require configuring a URL somewhere.

**Comment by alexduf** [comment]
Is Github enterprise literally swapping the domain name for another one?

**Comment by ntkoopman** [comment]
Yes, the other change is that the api is not hosted on a subdomain. So if Github is at hosted `https://custom.url/` then the api is at `https://custom.url/api/v3/notifications` and the overview is at `https://custom.url/notifications`

**Comment by jonathany70** [comment]
You may also need to support the various ways to authenticate with GHE, including Personal access tokens, etc

**Comment by wykapedia** [comment]
I can take a snag at this one.

**Comment by alexduf** [comment]
much appreciated!

**Comment by alexduf** [comment]
Hi @wykapedia @ntkoopman @jonathany70 

@Danmanirl has taken the time to raise a PR to support this feature. I was wondering if any of you had the capability to test the branch? I'm unfortunately away from a linux desktop on my day to day job now which makes it harder for me to maintain the project.

https://github.com/alexduf/gnome-github-notifications/pull/23

**Comment by brianwyka** [comment]
Can you share information on how to test the snapshot?

**Comment by alexduf** [comment]
>Can you share information on how to test the snapshot?

You can clone the repository locally, and checkout the right branch. Here's the instructions: https://github.com/alexduf/gnome-github-notifications#the-manual-way

**Comment by jonathan-r-young** [comment]
I have installed it, and modified the reference to github.com to use my github.ibm.com github enterprise instance. Will let you know how it goes. Fedora 31, Wayland

**Comment by jonathan-r-young** [comment]
So far so good - I missed the popup alert, but the status bar and link to the notification works, configured for enterprise github

**Comment by alexduf** [comment]
The extension has been approved for release, you should be able to download it from the gnome extension website now!
